# Generated by Django 5.2.8 on 2025-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twobeats_upload', '0002_alter_tag_options_alter_music_music_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_like_count',
            field=models.IntegerField(default=0, verbose_name='좋아요수'),
        ),
    ]
